const DEFAULTS={
 about:{eyebrow:'Profile',heading:'Building a career at the intersection of <em>cybersecurity</em>, technology and creativity.',paragraphs:['I am a motivated cybersecurity undergraduate at NSBM Green University with a strong foundation in network security, ethical hacking, risk assessment, access control, vulnerability assessment and incident response.','Alongside my technical studies, I create promotional content, photographs and videos for university activities. I enjoy transforming ideas into clear digital experiences, collaborating with teams and continuously improving my technical and communication skills.'],links:[{id:'l1',label:'Email me ↗',url:'mailto:abhishekparindya2007@gmail.com'},{id:'l2',label:'LinkedIn ↗',url:'https://www.linkedin.com/in/abhishek-parindya-326512411/'},{id:'l3',label:'GitHub ↗',url:'https://github.com/abhishekparindya2004'},{id:'l4',label:'Devpost ↗',url:'https://devpost.com/abhishekparindya2007may3?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav'},{id:'l5',label:'Unstop ↗',url:'https://unstop.com/u/abhispar56183'}]},
 projects:[{id:'p1',title:'Red Pulse',meta:'HTML • CSS • JavaScript',description:'Responsive online news platform with category-based sections, modern UI, mobile-friendly layouts and interactive navigation.',url:'https://github.com/abhishekparindya2004',image:''},{id:'p2',title:'Zey-AI',meta:'Artificial Intelligence Project',description:'AI-powered assistant prototype focused on improving user interaction and productivity through an accessible interface.',url:'https://github.com/abhishekparindya2004',image:''},{id:'p3',title:'Citadel',meta:'Cybersecurity / Technology Project',description:'Technology-focused application demonstrating secure development principles and structured project architecture.',url:'https://github.com/abhishekparindya2004',image:''}],
 education:[{id:'e1',period:'2026 — Present',title:'Major in Cyber Security',details:'NSBM Green University • Victoria University affiliated degree'},{id:'e2',period:'2024 — 2025',title:'Information Technology Diploma Level',details:'ESOFT Metro Campus'},{id:'e3',period:'2023',title:'G.C.E. Ordinary Level Examination',details:'Ecole International School, Kandy'},{id:'e4',period:'2017',title:'G.C.E. Scholarship Examination',details:'Gamini Dissanayake College, Hasalaka'}],
 coreSkills:['Project Management','Cybersecurity Fundamentals','Teamwork','Time Management','Leadership','Effective Communication','Critical Thinking','Digital Marketing'],tools:['Java','Python','JavaScript','HTML5','CSS3','SQL','Git','GitHub','VS Code','Microsoft Office','Wireshark','VirtualBox','Linux','Azure SQL'],cyberSkills:['Network Security','Ethical Hacking','Risk Assessment','Access Control','Vulnerability Assessment','Security Fundamentals','Incident Response'],languages:['English — Fluent','Sinhala — Fluent','Tamil — Basic'],
 process:[{id:'s1',number:'01',icon:'⌕',title:'Discover',description:'Understand the goals, audience, risks and success criteria.'},{id:'s2',number:'02',icon:'◇',title:'Plan',description:'Define scope, structure, tools and a practical delivery path.'},{id:'s3',number:'03',icon:'✎',title:'Design',description:'Create clear layouts and secure, user-focused solutions.'},{id:'s4',number:'04',icon:'</>',title:'Build',description:'Develop, test and refine with attention to detail.'},{id:'s5',number:'05',icon:'➤',title:'Deliver',description:'Document, communicate and improve from feedback.'}],
 activities:[{id:'c1',type:'club',title:'NSBM NFORCE Club',meta:'2026 — Present',description:'Content Creator, Photographer & Videographer. Create promotional content, capture event media, edit multimedia and collaborate with the media team.'},{id:'c2',type:'club',title:'NSBM Speakers Club',meta:'2025',description:'Active Member. Participate in public-speaking sessions, communication workshops, competitions and collaborative learning activities.'},{id:'w1',type:'workshop',title:'HackOps Cybersecurity Workshop',meta:'2025 • NSBM Green University',description:''},{id:'w2',type:'workshop',title:'Cybersecurity Awareness Workshop',meta:'2025 • NSBM Green University',description:''},{id:'w3',type:'workshop',title:'AI Puppet Master Workshop',meta:'2024 • ESOFT Metro Campus',description:''}],
 approach:{quote:'Good security is not only about stopping threats. It is also about creating systems people can trust.',signature:'Abhishek'},
 achievements:[{id:'a1',year:'2025',title:'Speech Olympics',details:'Semi-finalist • NSBM Green University',certificateUrl:'',certificateData:''},{id:'a2',year:'2024',title:'AI Puppet Master Certification',details:'Participation • ESOFT Metro Campus',certificateUrl:'',certificateData:''},{id:'a3',year:'2023',title:'Inter-School Basketball Championship',details:'Second place • Ecole International School',certificateUrl:'',certificateData:''},{id:'a4',year:'2017',title:'Inter-School Chess Tournament',details:'Second place • Sri Sumangala College, Kandy',certificateUrl:'',certificateData:''}],gallery:[],feedback:[],
 contact:{heading:'LET’S BUILD\nSOMETHING <em>SECURE.</em>',intro:'I’m open to cybersecurity internships, collaborative projects, creative media work and opportunities where I can learn, contribute and grow.',buttonText:'Start a conversation',email:'abhishekparindya2007@gmail.com',phone1:'+94 76 224 2905',phone2:'+94 77 824 8434',location:'274, Ampitiya, Kandy, Sri Lanka',links:[]},
 settings:{quote:'“Security is strongest when thoughtful design and responsible technology work together.”',intro:'I combine cybersecurity knowledge, creative media and web development to build secure, useful and visually engaging digital experiences.',projectSuffix:'+'}
};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>JSON.parse(JSON.stringify(x));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function mergeData(raw={}){return {...clone(DEFAULTS),...raw,about:{...clone(DEFAULTS.about),...(raw.about||{})},approach:{...clone(DEFAULTS.approach),...(raw.approach||{})},contact:{...clone(DEFAULTS.contact),...(raw.contact||{})},settings:{...clone(DEFAULTS.settings),...(raw.settings||{})}}}
let data=clone(DEFAULTS);
let activeGalleryFilter='All';
let lastServerSnapshot='';
async function syncFromServer(force=false){
 try{
  const remote=await PortfolioAPI.getData();
  if(!remote)return;
  const snapshot=JSON.stringify(remote);
  if(force||snapshot!==lastServerSnapshot){
   lastServerSnapshot=snapshot;
   data=mergeData(remote);
   renderAll();
  }
 }catch(err){console.error('Shared website data unavailable:',err)}
}
function tags(id,items){const el=$(id);if(el)el.innerHTML=(items||[]).map(x=>`<span>${esc(x)}</span>`).join('')}
function renderAbout(){$('#aboutEyebrow').textContent=data.about.eyebrow;$('#aboutHeading').innerHTML=data.about.heading;$('#aboutParagraphs').innerHTML=data.about.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('');$('#aboutLinks').innerHTML=data.about.links.map(l=>`<a href="${esc(l.url)}" ${/^https?:/.test(l.url)?'target="_blank" rel="noopener"':''}>${esc(l.label)}</a>`).join('')}
function renderStats(){$('#projectStat').textContent=String(data.projects.length).padStart(2,'0')+(data.settings.projectSuffix||'');$('#toolStat').textContent=String(data.tools.length).padStart(2,'0')+'+';$('#clubStat').textContent=String(data.activities.filter(x=>x.type==='club').length).padStart(2,'0');$('.hero-side blockquote').textContent=data.settings.quote;$('.hero .intro').textContent=data.settings.intro}
function renderProjects(){$('#projectGrid').innerHTML=data.projects.map((p,i)=>`<article class="project-card reveal visible" data-id="${p.id}"><div class="project-visual ${p.image?'dynamic':''}" ${p.image?`style="background-image:url('${esc(p.image)}')"`:''}>${p.image?'':`<div class="project-fallback">${esc(p.title.slice(0,2).toUpperCase())}</div>`}</div><div class="project-meta"><span class="project-no">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(p.title)}</h3><p>${esc(p.meta)}</p><p>${esc(p.description)}</p></div><span class="arrow">↗</span></div></article>`).join('');$$('#projectGrid .project-card').forEach(c=>c.onclick=()=>{const p=data.projects.find(x=>x.id===c.dataset.id);if(p?.url)window.open(p.url,'_blank')})}
function renderEducation(){$('#educationTimeline').innerHTML=data.education.map(e=>`<div class="timeline-item"><span>${esc(e.period)}</span><h3>${esc(e.title)}</h3><p>${esc(e.details)}</p></div>`).join('');tags('#coreSkillTags',data.coreSkills);tags('#toolTags',data.tools);tags('#cyberSkillTags',data.cyberSkills);tags('#languageTags',data.languages)}
function renderApproach(){$('#processList').innerHTML=data.process.map(s=>`<div><b>${esc(s.number)}</b><span class="icon">${esc(s.icon)}</span><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></div>`).join('');$('#clubCards').innerHTML=data.activities.filter(x=>x.type==='club').map(a=>`<article><b>${esc(a.title)}</b><small>${esc(a.meta)}</small><p>${esc(a.description)}</p></article>`).join('');$('#workshopCards').innerHTML=data.activities.filter(x=>x.type==='workshop').map(a=>`<article><b>${esc(a.title)}</b><small>${esc(a.meta)}</small>${a.description?`<p>${esc(a.description)}</p>`:''}</article>`).join('');$('#approachQuote').textContent=data.approach.quote;$('#approachSignature').textContent=data.approach.signature}
function renderAchievements(){$('#achievementList').innerHTML=data.achievements.map(a=>`<button data-id="${a.id}"><span>${esc(a.year)}</span><h3>${esc(a.title)}</h3><p>${esc(a.details)}</p><span class="cert-status">${a.certificateUrl||a.certificateData?'View certificate ↗':'Upload pending'}</span></button>`).join('');$$('#achievementList button').forEach(b=>b.onclick=()=>openCertificate(b.dataset.id))}
function normalizeDrive(u){return u.includes('/view')?u.replace('/view','/preview'):u}function openCertificate(id){const a=data.achievements.find(x=>x.id===id),source=a.certificateData||a.certificateUrl;$('#certificateTitle').textContent=a.title;$('#certificateViewer').innerHTML=!source?'<div class="certificate-placeholder">The certificate has not been uploaded yet.</div>':source.startsWith('data:application/pdf')||source.includes('drive.google.com')?`<iframe src="${esc(normalizeDrive(source))}"></iframe>`:`<img src="${esc(source)}" alt="${esc(a.title)} certificate">`;openModal('certificateModal')}
function renderGallery(){
 const grid=$('#galleryGrid');
 if(!grid)return;
 const seen=new Set();
 const items=(data.gallery||[]).filter(item=>{
   const image=String(item.image||'').trim();
   const key=image?`image:${image}`:`meta:${String(item.title||'').trim().toLowerCase()}|${String(item.category||'').trim().toLowerCase()}`;
   if(seen.has(key))return false;
   seen.add(key);
   return true;
 }).sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));
 grid.innerHTML=items.length?items.map(x=>{
   const tech=String(x.technologies||'').split(',').map(v=>v.trim()).filter(Boolean);
   return `<article class="image-card" tabindex="0" role="button" data-gallery-id="${esc(x.id)}">
    <div class="image-card-media">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title)}" loading="lazy" decoding="async">`:`<div class="gallery-image-fallback">${esc((x.title||'AP').slice(0,2).toUpperCase())}</div>`}</div>
    <div class="image-card-details">
      <div class="image-card-title-row"><h4>${esc(x.title||'Untitled project')}</h4>${x.url?`<a class="image-card-link" href="${esc(x.url)}" target="_blank" rel="noopener" aria-label="Open ${esc(x.title)}">↗</a>`:''}</div>
      ${x.category?`<span class="image-card-category">${esc(x.category)}</span>`:''}
      <p>${esc(x.description||'A selected project visual from my portfolio.')}</p>
      ${tech.length?`<div class="image-card-tech">${tech.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}
    </div>
   </article>`;
 }).join(''):'<div class="empty-state gallery-wide-empty">No gallery images have been uploaded yet.</div>';
 $$('#galleryGrid .image-card').forEach(card=>{
   const open=()=>{const item=items.find(x=>String(x.id)===card.dataset.galleryId);if(!item||!item.image)return;$('#galleryModalImage').src=item.image;$('#galleryModalImage').alt=(item.title||'Gallery image');$('#galleryModalTitle').textContent=item.title||'Project image';$('#galleryModalDescription').textContent=item.description||'';openModal('galleryModal')};
   card.addEventListener('click',e=>{if(!e.target.closest('a'))open()});
   card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('a')){e.preventDefault();open()}});
 });
}
function avatarHTML(f){return f.avatar?`<img class="feedback-avatar" src="${esc(f.avatar)}" alt="${esc(f.name)} profile image" loading="lazy">`:`<div class="feedback-avatar">${esc((f.name||'?').slice(0,1).toUpperCase())}</div>`}function renderFeedback(){const track=$('#feedbackTrack');if(!track)return;const feedback=[...(data.feedback||[])].sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));track.innerHTML=feedback.length?feedback.map(f=>{const rating=Math.max(0,Math.min(5,Number(f.rating)||0));const date=new Date(f.created||Date.now()).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});return `<article class="feedback-card">${avatarHTML(f)}<div class="feedback-person"><h3>${esc(f.name)}</h3><small>${esc(f.category||'Community feedback')} · ${date}</small></div><div class="stars" aria-label="${rating} out of 5 stars">${'★'.repeat(rating)}${'☆'.repeat(5-rating)}</div><p class="feedback-message">${esc(f.message)}</p></article>`}).join(''):'<div class="feedback-empty">Be the first person to leave thoughtful feedback.</div>'}
function renderContact(){
 const c=data.contact;
 $('#contactHeading').innerHTML=c.heading.replace(/\n/g,'<br>');$('#contactIntro').textContent=c.intro;
 const button=$('#contactButton');button.textContent=c.buttonText;button.removeAttribute('href');button.setAttribute('role','button');button.tabIndex=0;
 const cleanPhone=(c.phone1||c.phone2||'').replace(/[^+\d]/g,'');
 const whatsapp=cleanPhone?`https://wa.me/${cleanPhone.replace(/^\+/,'')}?text=${encodeURIComponent('Hello Abhishek, I visited your portfolio and would like to start a conversation.')}`:'';
 const choices=[
  c.email&&{icon:'✉',label:'Email',detail:c.email,url:'mailto:'+c.email},
  cleanPhone&&{icon:'◉',label:'WhatsApp',detail:c.phone1||c.phone2,url:whatsapp,target:'_blank'},
  cleanPhone&&{icon:'☎',label:'Phone call',detail:c.phone1||c.phone2,url:'tel:'+cleanPhone}
 ].filter(Boolean);
 const choiceGrid=$('#contactChoiceGrid');if(choiceGrid)choiceGrid.innerHTML=choices.map(x=>`<a class="contact-choice-option" href="${esc(x.url)}" ${x.target?'target="_blank" rel="noopener"':''}><span class="contact-choice-icon">${x.icon}</span><span><strong>${esc(x.label)}</strong><small>${esc(x.detail)}</small></span><b>↗</b></a>`).join('');
 const openChoices=()=>openModal('contactChoiceModal');button.onclick=openChoices;button.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openChoices()}};
 $('.contact-details').innerHTML=`<a href="mailto:${esc(c.email)}"><span>✉</span>${esc(c.email)}</a>${c.phone1?`<a href="tel:${esc(c.phone1.replace(/\s/g,''))}"><span>☎</span>${esc(c.phone1)}</a>`:''}${c.phone2?`<a href="tel:${esc(c.phone2.replace(/\s/g,''))}"><span>☎</span>${esc(c.phone2)}</a>`:''}<p><span>⌖</span>${esc(c.location)}</p>${c.links.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener"><span>↗</span>${esc(l.label)}</a>`).join('')}`
}
function renderAll(){renderAbout();renderStats();renderProjects();renderEducation();renderApproach();renderAchievements();renderGallery();renderFeedback();renderContact()}
function fileToData(file){return new Promise((res,rej)=>{if(!file)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('#feedbackForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),file=$('#feedbackAvatar').files[0],button=e.target.querySelector('button');let avatar=fd.get('avatarUrl')||'';if(file)avatar=await fileToData(file);const feedback={id:crypto.randomUUID(),name:fd.get('name'),email:fd.get('email'),category:fd.get('category'),rating:fd.get('rating'),message:fd.get('message'),avatar,created:new Date().toISOString()};button.disabled=true;try{await PortfolioAPI.addFeedback(feedback);await syncFromServer(true);e.target.reset();const thanks=$('#feedbackThankYou');if(thanks){thanks.textContent=`Thank you, ${feedback.name}! Your feedback has been published and is now visible on every device.`;thanks.hidden=false;clearTimeout(thanks._timer);thanks._timer=setTimeout(()=>thanks.hidden=true,7000)}}catch(err){alert('Your feedback could not be saved: '+err.message)}finally{button.disabled=false}});
$('#aiFab').onclick=()=>$('#aiPanel').classList.toggle('open');$('#closeAi').onclick=()=>$('#aiPanel').classList.remove('open');$('#aiForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#aiInput').value.trim();if(!q)return;addMsg(q,'user-msg');$('#aiInput').value='';setTimeout(()=>addMsg(answerAI(q),'bot-msg'),250)});function addMsg(t,c){const d=document.createElement('div');d.className=c;d.textContent=t;$('#aiMessages').appendChild(d);$('#aiMessages').scrollTop=$('#aiMessages').scrollHeight}function answerAI(q){q=q.toLowerCase();if(q.includes('project'))return `Abhishek currently showcases ${data.projects.length} featured projects: ${data.projects.map(p=>p.title).join(', ')}.`;if(q.includes('skill')||q.includes('tool'))return `His technical stack includes ${data.tools.join(', ')}.`;if(q.includes('education'))return data.education.map(e=>`${e.title} — ${e.details}`).join('; ');if(q.includes('contact'))return `Email: ${data.contact.email}. Phone: ${data.contact.phone1}. Location: ${data.contact.location}.`;return 'I can help with Abhishek’s projects, education, skills, activities, achievements and contact details.'}
const menu=$('.menu-toggle'),nav=$('.nav-links');menu.onclick=()=>{const o=nav.classList.toggle('open');menu.setAttribute('aria-expanded',o)};$$('.nav-links a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));$('#dashboardLink')?.addEventListener('click',e=>{e.preventDefault();window.location.href='./admin.html'});const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));window.addEventListener('pointermove',e=>{const g=$('.cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});$('#year').textContent=new Date().getFullYear();function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));renderAll();syncFromServer(true);setInterval(()=>syncFromServer(false),5000);window.addEventListener('focus',()=>syncFromServer(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncFromServer(true)});
